previewsEnabled: true

services:
  - type: web
    name: shopping-site
    env: python
    region: oregon
    plan: starter
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: false
    envVars:
    - key: DB_URL
      fromDatabase:
        name: shopping-database
        property: connectionString
    
databases:
  - name: shopping-database
    databaseName: shopping
